# Generated by Django 3.2 on 2022-03-07 19:55

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[account.validators.validate_phone_no, account.validators.validate_length_phone_no]),
        ),
    ]
