# Generated by Django 3.2 on 2022-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220221_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male'), ('C', 'Custom'), ('R', 'Rather not say')], max_length=1, null=True),
        ),
    ]
