# Generated by Django 3.2 on 2022-02-23 22:04

import account.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_email_confirmed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.manager.UserManager()),
            ],
        ),
    ]
