# Generated by Django 3.2 on 2022-02-21 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='category',
        ),
        migrations.AddField(
            model_name='email',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profilecontact',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_page.signature'),
        ),
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='profilecontact',
            name='owner',
        ),
        migrations.AddField(
            model_name='profilecontact',
            name='owner',
            field=models.ManyToManyField(related_name='contact_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signature',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SignatureCategory',
        ),
    ]
