# Generated by Django 3.2 on 2022-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0002_auto_20220221_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
