# Generated by Django 3.2 on 2022-02-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0003_alter_label_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Files'),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver',
            field=models.ManyToManyField(related_name='receivers', to='web_page.ProfileContact'),
        ),
    ]
