# Generated by Django 3.2 on 2022-02-26 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web_page.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_page', '0005_email_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='is_inbox',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='email',
            name='receiver',
        ),
        migrations.AddField(
            model_name='email',
            name='receiver_bcc',
            field=models.ManyToManyField(related_name='receivers_bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='receiver_cc',
            field=models.ManyToManyField(related_name='receivers_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='receiver_to',
            field=models.ManyToManyField(related_name='receivers_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilecontact',
            name='other_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profilecontact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Files', validators=[web_page.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.ManyToManyField(null=True, related_name='labels', to='web_page.Label'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='profilecontact',
            unique_together={('user', 'email')},
        ),
        migrations.RemoveField(
            model_name='profilecontact',
            name='owner',
        ),
    ]
