# Generated by Django 3.2 on 2022-03-01 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_page', '0006_auto_20220226_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_page.email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, related_name='labels', to='web_page.Label'),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver_bcc',
            field=models.ManyToManyField(blank=True, null=True, related_name='receivers_bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver_cc',
            field=models.ManyToManyField(blank=True, null=True, related_name='receivers_cc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_page.signature'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
