# Generated by Django 3.2 on 2022-03-08 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_page', '0008_label_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='labels', to='web_page.Label'),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver_bcc',
            field=models.ManyToManyField(blank=True, related_name='receivers_bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver_cc',
            field=models.ManyToManyField(blank=True, related_name='receivers_cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
