# Generated by Django 3.2 on 2022-03-08 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_page', '0009_auto_20220308_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='receiver_bcc',
            field=models.ManyToManyField(blank=True, null=True, related_name='receivers_bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver_cc',
            field=models.ManyToManyField(blank=True, null=True, related_name='receivers_cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
