# Generated by Django 3.2 on 2022-03-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_page', '0012_emailfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
